eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:  # 健康检查，否则Eureka会进入保护模式
      enabled: true
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
server:
  port: 8763
spring:
  application:
    name: service-hi